---
- name: Actualizar ArchLinux con Yay
  hosts: all
  become: true
  tasks:
    - name: Verificar si yay está instalado
      stat:
        path: /usr/bin/yay
      register: yay_installed
      failed_when: false
      changed_when: false
    - name: Actualizar paquetes con yay
      shell: |
        yay -Syu --noconfirm
      register: result
      changed_when: result.stdout != ""
      when: yay_installed.stat.exists

